Homepage:
    pattern:  /
    defaults: { _controller: "Application:Index:index"}

LastUrl:
    pattern: /api/lasturl
    defaults: { _controller: "Application:Api:getLastUrl" }

LastPrice:
    pattern: /api/lastprice
    defaults: { _controller: "Application:Api:getLastPrice" }

Uploadfile:
    pattern: /api/uploadfile
    defaults: { _controller: "Application:Api:uploadFile" }

Downloadfile:
    pattern: /api/downloadfile
    defaults: { _controller: "Application:Api:downloadfile" }

SavePurchase:
    pattern: /api/savepurchase
    defaults: { _controller: "Application:Api:savePurchase" }